name: HPV-1.0dev
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  # Add required software dependencies here
  - fastqc=0.11.8
  - trim-galore=0.6.2
  - bowtie2=2.3.4.1
  - samtools=1.9
  - bedtools=2.28.0
  - deeptools=3.3.0
  - python=3.6
  - pyfaidx=0.5.8
  - pysam=0.15.3
  - pandas=1.0.3
  - multiqc=1.8
  - blat=35
